name: GenerateScintillaImpl
on:
  push:
    paths:
      - '.github/workflows/GenerateScintillaImpl.yml'
      - 'scintilla/include/Scintilla.iface'
      - 'jsp64/ScintillaImpl.mjs'
      - 'jsp64/ScintillaImpl.template.hpp'

jobs:
  GenerateScintillaImpl:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: GenerateScintillaImpl
      working-directory: jsp64
      run: |
        node ScintillaImpl.mjs

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ScintillaImpl
        path: jsp64/ScintillaImpl.hpp
