name: GenerateScintillaImpl
on: [push, pull_request]
jobs:
  GenerateScintillaImpl:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: GenerateScintillaImpl
      run: |
        mkdir upload
        cd jsp3 && node ScintillaImpl.mjs
        copy ScintillaImpl.hpp ..\upload

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ScintillaImpl
        path: upload
