name: GenerateScintillaImpl
on:
  push:
    paths:
      - '.github/workflows/GenerateScintillaImpl.yml'
      - 'scintilla/include/Scintilla.iface'
      - 'scintilla/jsp3/ScintillaImpl.template.hpp'

jobs:
  GenerateScintillaImpl:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: GenerateScintillaImpl
      working-directory: jsp3
      run: |
        node ScintillaImpl.mjs

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ScintillaImpl
        path: jsp3/ScintillaImpl.hpp
